baseURL = "https://vojtamares.com/"
languageCode = "en-us"
DefaultContentLanguage = "en"
enableEmoji = true
googleAnalytics = "G-7SJ8913NW3"

[markup]
  [markup.highlight]
    codeFences = true
    style = "native"
    tabWidth = 4
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true

[outputFormats]
  [outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"

[author]
  name = "Vojtěch Mareš"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "blog"
  # posts per list page
  paginate = 4
  [params.links]
    [[params.links.dev]]
      identifier = "github"
      name = "github"
      url = "https://github.com/vojtamares"
    [[params.links.dev]]
      identifier = "twitter"
      name = "twitter"
      url = "https://twitter.com/vojtamares_dev"

[languages]
  [languages.en]
    languageName = "English"
    title = "Vojtěch Mareš - Software engineer, Freelancer"
    subtitle = "Hello, my name is Vojtěch Mareš. I'm from Czech Republic and I am a software and devops engineer, freelancer."
    keywords = "software engineer, developer, programmer, vojtěch mareš, vojta mareš, freelancer, web developer"
    copyright = "Vojtěch Mareš | Everything is mine here"
    weight = 1

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "home"
        url = "/"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "blog"
        url = "/blog"
  [languages.cs]
    languageName = "Čeština"
    title = "Vojtěch Mareš - Softwarový inženýr na volné noze"
    subtitle = "Ahoj, jmenuji se Vojtěch Mareš. Jsem softwarový a devops inženýr na volné noze (OSVČ)."
    keywords = "softwarový indženýr, vývojář, programátor, vojtěch mareš, vojta mareš, freelancer, osvč, na volné noze, web developer"
    copyright = "Vojtěch Mareš | Všechno tu je moje"
    weight = 2
    [[languages.cs.menu.main]]
      identifier = "home"
      name = "home"
      url = "/"
    [[languages.en.menu.main]]
      identifier = "about"
      name = "about"
      url = "/about"
    [[languages.en.menu.main]]
      identifier = "blog"
      name = "blog"
      url = "/blog"
      
[permalinks]
  "/gitlab" = "https://gitlab.vojtamares.com/users/sign_in"
