[[redirects]]
    from = "/gitlab"
    to = "https://gitlab.mareshq.com/users/sign_in"

[[redirects]]
    from = "http://vojtamares.com"
    to = "https://vojtechmares.com"
    status = 301
    force = true

[[redirects]]
    from = "https://vojtamares.com"
    to = "https://vojtechmares.com"
    status = 301
    force = true

[[redirects]]
    from = "http://www.vojtamares.com"
    to = "https://vojtechmares.com"
    status = 301
    force = true

[[redirects]]
    from = "https://www.vojtechmares.com"
    to = "https://vojtechmares.com"
    status = 301
    force = true
    
[[redirects]]
    from = "https://vojtamares.cz"
    to = "https://vojtechmares.com"
    status = 301
    force = true    
    
[[redirects]]
    from = "https://www.vojtamares.cz"
    to = "https://vojtechmares.com"
    status = 301
    force = true
